config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "home#index"
  resources :recipes, only: [:show, :new, :create, :edit, :update]
  resources :cuisines, only: [:show, :new, :create]
  resources :recipe_types, only: [:show, :new, :create]
  get "/busca", to: "recipes#buscar"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cuisine.rb
class Cuisine < ApplicationRecord
  has_many :recipes
  validates :name, presence: { message: 'Você deve informar o nome da cozinha' }
  validates :name, uniqueness: { message: 'Esta cozinha já foi cadastrada' }
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :cuisine
  belongs_to :recipe_type
  validates :title, :difficulty, :cook_time, :ingredients, :cook_method, presence: true
  
  has_attached_file :avatar
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/
end

app/models/recipe_type.rb
class RecipeType < ApplicationRecord
  has_many :recipes
  validates :name, presence: {message: 'Você deve informar o nome do tipo de receita'}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cuisines_controller.rb
class CuisinesController < ApplicationController

  def show
    id = params[:id]
    @cuisine = Cuisine.find(id) 
  end

  def new
    @cuisine = Cuisine.new
  end

  def create
    @cuisine = Cuisine.new(cuisine_params)
    if @cuisine.save
        redirect_to cuisine_path(@cuisine.id)
    else
      render :new
    end
  end

  def cuisine_params
    params.require(:cuisine).permit(:name)
  end
  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @recipes = Recipe.all
    @cuisines = Cuisine.all
    @recipe_types = RecipeType.all
  end
end

app/controllers/recipe_types_controller.rb
class RecipeTypesController < ApplicationController

  def show
    @recipe_type = RecipeType.find(params[:id])
  end

  def new
    @recipe_type = RecipeType.new
  end

  def create
    @recipe_type = RecipeType.new(params.require(:recipe_type).permit(:name))
    if @recipe_type.save
      redirect_to recipe_type_path(@recipe_type.id)
    else
      render :new
    end
  end

end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def show
    id = params[:id]
    @recipe = Recipe.find(id)
  end

  def new
    @recipe = Recipe.new
    @cuisines = Cuisine.all
    @recipe_types = RecipeType.all
  end

  def create
    @recipe = Recipe.new(recipe_params)
    
    if @recipe.save
      redirect_to recipe_path(@recipe.id)
    else
      @cuisines = Cuisine.all
      @recipe_types = RecipeType.all
      flash[:error] = 'Você deve informar todos os dados da receita'
      render 'new'
    end
  end

  def edit
    @recipe_types = RecipeType.all
    @cuisines = Cuisine.all
    @recipe = Recipe.find(params[:id])
  end

  def update
    @recipe = Recipe.find(params[:id])
    
    if @recipe.update(recipe_params) 
      flash[:notice] = 'Suas alterações foram salvas com sucesso!'
      redirect_to recipe_path(@recipe.id)
    else
      @cuisines = Cuisine.all
      @recipe_types = RecipeType.all
      flash[:alert] = 'Você deve informar todos os dados da receita'
      render :edit
    end
  end

  def buscar
    nome = params[:nome]
    @busca = Recipe.where(title: nome)
    if @busca.empty?
      flash[:alert] = 'Receita não encontrada!'
      redirect_to root_path
    else
      flash[:message] = 'Receita encontrada!'
    end
  end

  private

  def recipe_params
    params.require(:recipe).permit(:title, :recipe_type_id, :cuisine_id, :difficulty, :cook_time, :ingredients, :cook_method, :avatar)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/cuisines/new.html.erb
<%= @msg %>
<%= @cuisine.errors.full_messages %>
<%= form_for (@cuisine) do |f| %>
  <%= f.label :name, "Nome" %>
  <%= f.text_field :name %>
  <%= f.submit "Enviar"%>
<% end%>

app/views/cuisines/show.html.erb
<h1> <%= @cuisine.name %> </h1>

<% if @cuisine.recipes.empty? %>
  <p>Nenhuma receita encontrada para este tipo de cozinha</p>
<% end %>

<% @cuisine.recipes.each do |r| %>
  <h1><%= link_to(r.title, r) %></h1>
  <ul>
    <li><%= r.recipe_type.name %></li>
    <li><%= r.cuisine.name %></li>
    <li><%= r.difficulty %></li>
    <li><%= r.cook_time %> minutos</li>
  </ul>
<% end %>

app/views/home/index.html.erb
<h1>CookBook</h1>
<p>Bem-vindo ao maior livro de receitas online</p>

<%=link_to "Login", new_user_session_path %>

<% @recipes.each do |r| %>
  <h1><%= link_to(r.title, r) %></h1>
  <ul>
    <li><%= r.recipe_type.name %></li>
    <li><%= r.cuisine.name %></li>
    <li><%= r.difficulty %></li>
    <li><%= r.cook_time %> minutos</li>
  </ul>
<% end %>

<% @cuisines.each do |c| %>
  <%= link_to(c.name, c)%>
<% end %>

<% @recipe_types.each do |recipe_type| %>
  <%= link_to recipe_type.name, recipe_type %>
<% end %>

<% if user_signed_in? %>
  <p> Olá <%= current_user.email %> <p>
  <% else %>
    <%=link_to "Enviar uma receita", new_recipe_path%>
<% end %>

<%= form_tag("/busca", method: "get") do %>
  <%= label_tag(:nome, "Busca") %>
  <%= text_field_tag(:nome) %>
  <%= submit_tag("Buscar") %>
<%end%>

<h1> <%= flash[:alert] %> </h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyCookbook</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <div class="container">
      <%= notice %>
      <%= alert %>
      <%= yield %>
    </div>
    
  </body>
</html>

app/views/recipe_types/new.html.erb
<%= @recipe_type.errors.full_messages.each do |error_message| %>
  <p><%= error_message %></p>
<% end %>

<%= form_for @recipe_type do |recipe_type| %>
  <%= recipe_type.label :name, 'Nome' %>
  <%= recipe_type.text_field :name %>

  <%= recipe_type.submit 'Enviar' %>
<% end %>

app/views/recipe_types/show.html.erb
<h1><%= @recipe_type.name %></h1>

<% if @recipe_type.recipes.empty? %>
  <p>Nenhuma receita encontrada para este tipo de receitas</p>
<% end %>

<% @recipe_type.recipes.each do |recipe| %>
  <h1><%= recipe.title %></h1>
  <ul>
    <li><%= recipe.recipe_type.name %></li>
    <li><%= recipe.cuisine.name %></li>
    <li><%= recipe.difficulty %></li>
    <li><%= recipe.cook_time %> minutos</li>
  </ul>
<% end %>

app/views/recipes/buscar.html.erb
<h1> <%= flash[:message] %> </h1>

<%= @busca.each do |busca| %>

    <h1> <%= busca.title %> <h1>
    <p> <%= busca.recipe_type.name %> </p>
    <p> <%= busca.cuisine.name %> </p>
    <p> <%= busca.difficulty %> </p>
    <p> <%= busca.cook_time %> minutos </p>
    
    <h3>Ingredientes </h3>
    <p> <%= busca.ingredients %> </p>
    
    <h3> Como Preparar </h3>
    <p> <%= busca.cook_method %> </p>

<% end %>

app/views/recipes/edit.html.erb
<%= flash[:alert] %>

<%= form_for(@recipe) do |f| %>
  <%= f.label :title, "Título" %>
  <%= f.text_field :title %>

  <%= f.label :recipe_type_id, "Tipo da Receita" %>
  <%= f.collection_select :recipe_type_id, @recipe_types, :id, :name %>

  <%= f.label :cuisine_id, "Cozinha" %>
  <%= f.collection_select :cuisine_id, @cuisines, :id, :name %>

  <%= f.label :difficulty, "Dificuldade" %>
  <%= f.text_field :difficulty %>

  <%= f.label :cook_time, "Tempo de Preparo" %>
  <%= f.text_field :cook_time %>

  <%= f.label :ingredients, "Ingredientes" %>
  <%= f.text_area :ingredients %>

  <%= f.label :cook_method, "Como Preparar" %>
  <%= f.text_field :cook_method %>

  <%= f.submit "Enviar" %>
<% end %>

app/views/recipes/new.html.erb
<h1> Nova Receita </h1>

<%=flash[:error]%>

<%= form_for(@recipe, html: { multipart: true }) do |f| %>
  <%= f.label :title, "Título" %>
  <%= f.text_field :title %>

  <%= f.label :recipe_type_id, "Tipo da Receita" %>
  <%= f.collection_select :recipe_type_id, @recipe_types, :id, :name %>

  <%= f.label :cuisine_id, "Cozinha" %>
  <%= f.collection_select :cuisine_id, @cuisines, :id, :name %>

  <%= f.label :difficulty, "Dificuldade" %>
  <%= f.text_field :difficulty %>

  <%= f.label :cook_time, "Tempo de Preparo" %>
  <%= f.text_field :cook_time %>

  <%= f.label :ingredients, "Ingredientes" %>
  <%= f.text_area :ingredients %>

  <%= f.label :cook_method, "Como Preparar" %>
  <%= f.text_field :cook_method %>
  
  <%= f.label :avatar, "Foto" %>
  <%= f.file_field :avatar %>
  
  <%= f.submit "Enviar" %>
<% end %>

app/views/recipes/show.html.erb
<h1><%= flash[:notice] %></h1>

<h1><%= @recipe.title %></h1>

<h3>Detalhes</h3>
<p><%= @recipe.recipe_type.name %></p>
<p><%= @recipe.cuisine.name %></p>
<p><%= @recipe.difficulty %></p>
<p><%= @recipe.cook_time %> minutos</p>

<h3>Ingredientes</h3>
<p><%= @recipe.ingredients %></p>

<h3>Como Preparar</h3>
<p><%= @recipe.cook_method %></p>

<%= image_tag @recipe.avatar.url %>

<%= link_to 'Editar', edit_recipe_path(@recipe.id) %>
<%= link_to 'Voltar', root_path %>